const ClientTitle = document.querySelector("#clienttitle")
const ClientName = document.querySelector("#client-name")
const ClientLname = document.querySelector("#client-lname")
const ClientType = document.querySelector("#classType")
const ClientState = document.querySelector(".clientstate")
const ClientLga = document.querySelector(".select-lga")
const ClientEmail = document.querySelector("#email-address")
const clientPhone = document.querySelector("#clientphone")
//
const ClientHear = document.querySelector("#clienthear")
const ClientGender = document.querySelector("#clientgender")
const ClientGroup = document.querySelector(".select-course")
const clientCourse = document.querySelector(".clientcat")
const clientClass = document.querySelector("#clientclass")
const clientHour = document.querySelector(".clienthour")
const clientDuration = document.querySelector(".clientduration")
const clientClass = document.querySelector("#clientclass")
//
const Monday = document.querySelector("#monday")
const Tuesday = document.querySelector("#tuesday")
const Wednesday = document.querySelector("#wednesday")
const Thursday = document.querySelector("#thursday")
const Friday = document.querySelector("#friday")
const Saturday = document.querySelector("#saturday")
const Sunday = document.querySelector("#sunday")